package com.gzhou.eventing.util;


public final class Constants {

    // incoming hook for slack, generated by slack
    public final static String incomingWebHook = "https://hooks.slack.com/services/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";

    // github api
    public final static String changeUrlPrefix = "https://api.github.com/repos/";

    // github api
    public final static String rawFileUrlPrefix  = "https://raw.githubusercontent.com";

    // application url
    public final static String appGeneralPrefix  = "http://104.131.39.136:8080/eventweb/event";

    // Redis server url
    public final static String redisUrl  = "107.170.124.118";

    // Redis server port
    public final static int redisPort  = 6379;

    private Constants() {
    }
}
